name: MLflow Project CI

on:
  push:
    paths:
      - "MLProject/**"
  workflow_dispatch:

jobs:
  run-mlproject:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run MLflow Project
        run: |
          cd Workflow-CI/MLProject
          python modelling.py
